// flow-typed signature: bffe751d8fba50174e53bb06b24242b7
// flow-typed version: <<STUB>>/@mikestaub/gql2flow_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mikestaub/gql2flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mikestaub/gql2flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mikestaub/gql2flow/util/fetcher' {
  declare module.exports: any;
}

declare module '@mikestaub/gql2flow/util/fileIO' {
  declare module.exports: any;
}

declare module '@mikestaub/gql2flow/util/interface' {
  declare module.exports: any;
}

declare module '@mikestaub/gql2flow/util/module' {
  declare module.exports: any;
}

declare module '@mikestaub/gql2flow/util/polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mikestaub/gql2flow/index' {
  declare module.exports: $Exports<'@mikestaub/gql2flow'>;
}
declare module '@mikestaub/gql2flow/index.js' {
  declare module.exports: $Exports<'@mikestaub/gql2flow'>;
}
declare module '@mikestaub/gql2flow/util/fetcher.js' {
  declare module.exports: $Exports<'@mikestaub/gql2flow/util/fetcher'>;
}
declare module '@mikestaub/gql2flow/util/fileIO.js' {
  declare module.exports: $Exports<'@mikestaub/gql2flow/util/fileIO'>;
}
declare module '@mikestaub/gql2flow/util/interface.js' {
  declare module.exports: $Exports<'@mikestaub/gql2flow/util/interface'>;
}
declare module '@mikestaub/gql2flow/util/module.js' {
  declare module.exports: $Exports<'@mikestaub/gql2flow/util/module'>;
}
declare module '@mikestaub/gql2flow/util/polyfill.js' {
  declare module.exports: $Exports<'@mikestaub/gql2flow/util/polyfill'>;
}
