// flow-typed signature: d52edb6031dfc2b8f3e790046c472d58
// flow-typed version: <<STUB>>/@mikestaub/passport-slack_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mikestaub/passport-slack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mikestaub/passport-slack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mikestaub/passport-slack/lib/passport-slack/index' {
  declare module.exports: any;
}

declare module '@mikestaub/passport-slack/lib/passport-slack/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mikestaub/passport-slack/lib/passport-slack/index.js' {
  declare module.exports: $Exports<'@mikestaub/passport-slack/lib/passport-slack/index'>;
}
declare module '@mikestaub/passport-slack/lib/passport-slack/strategy.js' {
  declare module.exports: $Exports<'@mikestaub/passport-slack/lib/passport-slack/strategy'>;
}
