// flow-typed signature: ddefb97b8062d4aa8a1e8daba08ad95a
// flow-typed version: <<STUB>>/@mikestaub/simple-secrets_v2.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mikestaub/simple-secrets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mikestaub/simple-secrets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mikestaub/simple-secrets/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mikestaub/simple-secrets/bin.js' {
  declare module.exports: $Exports<'@mikestaub/simple-secrets/bin'>;
}
declare module '@mikestaub/simple-secrets/index' {
  declare module.exports: $Exports<'@mikestaub/simple-secrets'>;
}
declare module '@mikestaub/simple-secrets/index.js' {
  declare module.exports: $Exports<'@mikestaub/simple-secrets'>;
}
