// flow-typed signature: b7babdc00685cbc191d224b2640b1069
// flow-typed version: <<STUB>>/arangojs_v6.2.4/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'arangojs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'arangojs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'arangojs/lib/async/aql-query' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/arangojs' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/collection' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/connection' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/cursor' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/database' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/error' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/graph' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/index' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/route' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/btoa' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/btoa.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/bytelength' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/bytelength.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/error' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/joinPath' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/joinPath.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/multipart' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/multipart.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/request' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/request.node' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/request.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/types' {
  declare module.exports: any;
}

declare module 'arangojs/lib/async/util/xhr' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/aql-query' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/arangojs' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/collection' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/connection' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/cursor' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/database' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/error' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/graph' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/route' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/btoa' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/btoa.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/bytelength' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/bytelength.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/error' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/joinPath' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/joinPath.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/multipart' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/multipart.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/request' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/request.node' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/request.web' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/types' {
  declare module.exports: any;
}

declare module 'arangojs/lib/cjs/util/xhr' {
  declare module.exports: any;
}

declare module 'arangojs/lib/index' {
  declare module.exports: any;
}

declare module 'arangojs/lib/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'arangojs/lib/async/aql-query.js' {
  declare module.exports: $Exports<'arangojs/lib/async/aql-query'>;
}
declare module 'arangojs/lib/async/arangojs.js' {
  declare module.exports: $Exports<'arangojs/lib/async/arangojs'>;
}
declare module 'arangojs/lib/async/collection.js' {
  declare module.exports: $Exports<'arangojs/lib/async/collection'>;
}
declare module 'arangojs/lib/async/connection.js' {
  declare module.exports: $Exports<'arangojs/lib/async/connection'>;
}
declare module 'arangojs/lib/async/cursor.js' {
  declare module.exports: $Exports<'arangojs/lib/async/cursor'>;
}
declare module 'arangojs/lib/async/database.js' {
  declare module.exports: $Exports<'arangojs/lib/async/database'>;
}
declare module 'arangojs/lib/async/error.js' {
  declare module.exports: $Exports<'arangojs/lib/async/error'>;
}
declare module 'arangojs/lib/async/graph.js' {
  declare module.exports: $Exports<'arangojs/lib/async/graph'>;
}
declare module 'arangojs/lib/async/index.js' {
  declare module.exports: $Exports<'arangojs/lib/async/index'>;
}
declare module 'arangojs/lib/async/route.js' {
  declare module.exports: $Exports<'arangojs/lib/async/route'>;
}
declare module 'arangojs/lib/async/util/btoa.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/btoa'>;
}
declare module 'arangojs/lib/async/util/btoa.web.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/btoa.web'>;
}
declare module 'arangojs/lib/async/util/bytelength.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/bytelength'>;
}
declare module 'arangojs/lib/async/util/bytelength.web.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/bytelength.web'>;
}
declare module 'arangojs/lib/async/util/error.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/error'>;
}
declare module 'arangojs/lib/async/util/joinPath.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/joinPath'>;
}
declare module 'arangojs/lib/async/util/joinPath.web.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/joinPath.web'>;
}
declare module 'arangojs/lib/async/util/multipart.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/multipart'>;
}
declare module 'arangojs/lib/async/util/multipart.web.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/multipart.web'>;
}
declare module 'arangojs/lib/async/util/request.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/request'>;
}
declare module 'arangojs/lib/async/util/request.node.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/request.node'>;
}
declare module 'arangojs/lib/async/util/request.web.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/request.web'>;
}
declare module 'arangojs/lib/async/util/types.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/types'>;
}
declare module 'arangojs/lib/async/util/xhr.js' {
  declare module.exports: $Exports<'arangojs/lib/async/util/xhr'>;
}
declare module 'arangojs/lib/cjs/aql-query.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/aql-query'>;
}
declare module 'arangojs/lib/cjs/arangojs.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/arangojs'>;
}
declare module 'arangojs/lib/cjs/collection.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/collection'>;
}
declare module 'arangojs/lib/cjs/connection.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/connection'>;
}
declare module 'arangojs/lib/cjs/cursor.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/cursor'>;
}
declare module 'arangojs/lib/cjs/database.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/database'>;
}
declare module 'arangojs/lib/cjs/error.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/error'>;
}
declare module 'arangojs/lib/cjs/graph.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/graph'>;
}
declare module 'arangojs/lib/cjs/index.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/index'>;
}
declare module 'arangojs/lib/cjs/route.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/route'>;
}
declare module 'arangojs/lib/cjs/util/btoa.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/btoa'>;
}
declare module 'arangojs/lib/cjs/util/btoa.web.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/btoa.web'>;
}
declare module 'arangojs/lib/cjs/util/bytelength.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/bytelength'>;
}
declare module 'arangojs/lib/cjs/util/bytelength.web.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/bytelength.web'>;
}
declare module 'arangojs/lib/cjs/util/error.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/error'>;
}
declare module 'arangojs/lib/cjs/util/joinPath.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/joinPath'>;
}
declare module 'arangojs/lib/cjs/util/joinPath.web.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/joinPath.web'>;
}
declare module 'arangojs/lib/cjs/util/multipart.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/multipart'>;
}
declare module 'arangojs/lib/cjs/util/multipart.web.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/multipart.web'>;
}
declare module 'arangojs/lib/cjs/util/request.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/request'>;
}
declare module 'arangojs/lib/cjs/util/request.node.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/request.node'>;
}
declare module 'arangojs/lib/cjs/util/request.web.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/request.web'>;
}
declare module 'arangojs/lib/cjs/util/types.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/types'>;
}
declare module 'arangojs/lib/cjs/util/xhr.js' {
  declare module.exports: $Exports<'arangojs/lib/cjs/util/xhr'>;
}
declare module 'arangojs/lib/index.js' {
  declare module.exports: $Exports<'arangojs/lib/index'>;
}
declare module 'arangojs/lib/web.js' {
  declare module.exports: $Exports<'arangojs/lib/web'>;
}
