// flow-typed signature: 9e2200aa855f1edb4c83a2b22ed70ab6
// flow-typed version: <<STUB>>/aws-serverless-express_v3.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-serverless-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-serverless-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-serverless-express/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-serverless-express/index' {
  declare module.exports: $Exports<'aws-serverless-express'>;
}
declare module 'aws-serverless-express/index.js' {
  declare module.exports: $Exports<'aws-serverless-express'>;
}
declare module 'aws-serverless-express/middleware.js' {
  declare module.exports: $Exports<'aws-serverless-express/middleware'>;
}
