// flow-typed signature: ac535c5418e0ea1486a892e14ae55fd2
// flow-typed version: <<STUB>>/base64-url_v2.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'base64-url/index' {
  declare module.exports: $Exports<'base64-url'>;
}
declare module 'base64-url/index.js' {
  declare module.exports: $Exports<'base64-url'>;
}
