// flow-typed signature: 664b787a81888a2a6d5b78fbbfab9bec
// flow-typed version: <<STUB>>/compose-middleware_v4.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compose-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compose-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compose-middleware/lib/index' {
  declare module.exports: any;
}

declare module 'compose-middleware/lib/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compose-middleware/lib/index.js' {
  declare module.exports: $Exports<'compose-middleware/lib/index'>;
}
declare module 'compose-middleware/lib/index.spec.js' {
  declare module.exports: $Exports<'compose-middleware/lib/index.spec'>;
}
