// flow-typed signature: 995b242c31c1d3b1e90385dc4cf47925
// flow-typed version: <<STUB>>/dayjs_v1.6.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dayjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dayjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dayjs/dayjs.min' {
  declare module.exports: any;
}

declare module 'dayjs/locale/de' {
  declare module.exports: any;
}

declare module 'dayjs/locale/es' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ja' {
  declare module.exports: any;
}

declare module 'dayjs/locale/pt-br' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ru' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tr' {
  declare module.exports: any;
}

declare module 'dayjs/locale/zh-cn' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/advancedFormat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dayjs/dayjs.min.js' {
  declare module.exports: $Exports<'dayjs/dayjs.min'>;
}
declare module 'dayjs/locale/de.js' {
  declare module.exports: $Exports<'dayjs/locale/de'>;
}
declare module 'dayjs/locale/es.js' {
  declare module.exports: $Exports<'dayjs/locale/es'>;
}
declare module 'dayjs/locale/ja.js' {
  declare module.exports: $Exports<'dayjs/locale/ja'>;
}
declare module 'dayjs/locale/pt-br.js' {
  declare module.exports: $Exports<'dayjs/locale/pt-br'>;
}
declare module 'dayjs/locale/ru.js' {
  declare module.exports: $Exports<'dayjs/locale/ru'>;
}
declare module 'dayjs/locale/tr.js' {
  declare module.exports: $Exports<'dayjs/locale/tr'>;
}
declare module 'dayjs/locale/zh-cn.js' {
  declare module.exports: $Exports<'dayjs/locale/zh-cn'>;
}
declare module 'dayjs/plugin/advancedFormat.js' {
  declare module.exports: $Exports<'dayjs/plugin/advancedFormat'>;
}
