// flow-typed signature: 0b0a322b838bb7abf2c5871b3e99d4ef
// flow-typed version: <<STUB>>/edmonds-blossom_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'edmonds-blossom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'edmonds-blossom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'edmonds-blossom/app/blossom' {
  declare module.exports: any;
}

declare module 'edmonds-blossom/spec/blossomSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'edmonds-blossom/app/blossom.js' {
  declare module.exports: $Exports<'edmonds-blossom/app/blossom'>;
}
declare module 'edmonds-blossom/spec/blossomSpec.js' {
  declare module.exports: $Exports<'edmonds-blossom/spec/blossomSpec'>;
}
