// flow-typed signature: 3c5c956f3905e2d232d2c68c22bd0b2b
// flow-typed version: <<STUB>>/geo-distance_v0.1.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geo-distance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geo-distance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geo-distance/example/earth' {
  declare module.exports: any;
}

declare module 'geo-distance/example/map' {
  declare module.exports: any;
}

declare module 'geo-distance/lib/geo-distance' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geo-distance/example/earth.js' {
  declare module.exports: $Exports<'geo-distance/example/earth'>;
}
declare module 'geo-distance/example/map.js' {
  declare module.exports: $Exports<'geo-distance/example/map'>;
}
declare module 'geo-distance/lib/geo-distance.js' {
  declare module.exports: $Exports<'geo-distance/lib/geo-distance'>;
}
