// flow-typed signature: d19469defda6472a913185896db1c413
// flow-typed version: <<STUB>>/graphql-voyager_v1.0.0-rc.15/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-voyager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-voyager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-voyager/dist/voyager' {
  declare module.exports: any;
}

declare module 'graphql-voyager/dist/voyager.lib' {
  declare module.exports: any;
}

declare module 'graphql-voyager/dist/voyager.min' {
  declare module.exports: any;
}

declare module 'graphql-voyager/dist/voyager.worker' {
  declare module.exports: any;
}

declare module 'graphql-voyager/example/middleware/express' {
  declare module.exports: any;
}

declare module 'graphql-voyager/example/middleware/hapi' {
  declare module.exports: any;
}

declare module 'graphql-voyager/example/middleware/koa' {
  declare module.exports: any;
}

declare module 'graphql-voyager/example/schema' {
  declare module.exports: any;
}

declare module 'graphql-voyager/example/server' {
  declare module.exports: any;
}

declare module 'graphql-voyager/example/webpack-example/index' {
  declare module.exports: any;
}

declare module 'graphql-voyager/example/webpack-example/webpack.config' {
  declare module.exports: any;
}

declare module 'graphql-voyager/middleware/express' {
  declare module.exports: any;
}

declare module 'graphql-voyager/middleware/hapi' {
  declare module.exports: any;
}

declare module 'graphql-voyager/middleware/index' {
  declare module.exports: any;
}

declare module 'graphql-voyager/middleware/koa' {
  declare module.exports: any;
}

declare module 'graphql-voyager/middleware/render-voyager-page' {
  declare module.exports: any;
}

declare module 'graphql-voyager/postcss.config' {
  declare module.exports: any;
}

declare module 'graphql-voyager/src/graph/viz-worker.worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-voyager/dist/voyager.js' {
  declare module.exports: $Exports<'graphql-voyager/dist/voyager'>;
}
declare module 'graphql-voyager/dist/voyager.lib.js' {
  declare module.exports: $Exports<'graphql-voyager/dist/voyager.lib'>;
}
declare module 'graphql-voyager/dist/voyager.min.js' {
  declare module.exports: $Exports<'graphql-voyager/dist/voyager.min'>;
}
declare module 'graphql-voyager/dist/voyager.worker.js' {
  declare module.exports: $Exports<'graphql-voyager/dist/voyager.worker'>;
}
declare module 'graphql-voyager/example/middleware/express.js' {
  declare module.exports: $Exports<'graphql-voyager/example/middleware/express'>;
}
declare module 'graphql-voyager/example/middleware/hapi.js' {
  declare module.exports: $Exports<'graphql-voyager/example/middleware/hapi'>;
}
declare module 'graphql-voyager/example/middleware/koa.js' {
  declare module.exports: $Exports<'graphql-voyager/example/middleware/koa'>;
}
declare module 'graphql-voyager/example/schema.js' {
  declare module.exports: $Exports<'graphql-voyager/example/schema'>;
}
declare module 'graphql-voyager/example/server.js' {
  declare module.exports: $Exports<'graphql-voyager/example/server'>;
}
declare module 'graphql-voyager/example/webpack-example/index.jsx' {
  declare module.exports: $Exports<'graphql-voyager/example/webpack-example/index'>;
}
declare module 'graphql-voyager/example/webpack-example/webpack.config.js' {
  declare module.exports: $Exports<'graphql-voyager/example/webpack-example/webpack.config'>;
}
declare module 'graphql-voyager/middleware/express.js' {
  declare module.exports: $Exports<'graphql-voyager/middleware/express'>;
}
declare module 'graphql-voyager/middleware/hapi.js' {
  declare module.exports: $Exports<'graphql-voyager/middleware/hapi'>;
}
declare module 'graphql-voyager/middleware/index.js' {
  declare module.exports: $Exports<'graphql-voyager/middleware/index'>;
}
declare module 'graphql-voyager/middleware/koa.js' {
  declare module.exports: $Exports<'graphql-voyager/middleware/koa'>;
}
declare module 'graphql-voyager/middleware/render-voyager-page.js' {
  declare module.exports: $Exports<'graphql-voyager/middleware/render-voyager-page'>;
}
declare module 'graphql-voyager/postcss.config.js' {
  declare module.exports: $Exports<'graphql-voyager/postcss.config'>;
}
declare module 'graphql-voyager/src/graph/viz-worker.worker.js' {
  declare module.exports: $Exports<'graphql-voyager/src/graph/viz-worker.worker'>;
}
