// flow-typed signature: ffd42a28d3eee98dcb4e9e1542cc20f7
// flow-typed version: <<STUB>>/graphql-disable-introspection_v1.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-disable-introspection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-disable-introspection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-disable-introspection/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-disable-introspection/index' {
  declare module.exports: $Exports<'graphql-disable-introspection'>;
}
declare module 'graphql-disable-introspection/index.js' {
  declare module.exports: $Exports<'graphql-disable-introspection'>;
}
declare module 'graphql-disable-introspection/test.js' {
  declare module.exports: $Exports<'graphql-disable-introspection/test'>;
}
