// flow-typed signature: a532e362f546f5e5b22dadb4daa5021f
// flow-typed version: <<STUB>>/graphql-tools_v3.0.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-tools/dist/implementsAbstractType' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/Interfaces' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/isEmptyObject' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/isSpecifiedScalarType' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/Logger' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/mergeDeep' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/mock' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/schemaGenerator' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/schemaVisitor' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/defaultMergedResolver' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/delegateToSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/errors' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/index' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/introspectSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/linkToFetcher' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/makeRemoteExecutableSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/mergeSchemas' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/observableToAsyncIterable' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/resolveFromParentTypename' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/resolvers' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/schemaRecreation' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/typeFromAST' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/AddArgumentsAsVariables' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/AddTypenameToAbstract' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/CheckResultAndHandleErrors' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/ExpandAbstractTypes' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/ExtractField' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/FilterRootFields' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/FilterToSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/FilterTypes' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/index' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/RenameRootFields' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/RenameTypes' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/ReplaceFieldWithFragment' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/TransformRootFields' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/transforms' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/transformSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/visitSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/transforms/WrapQuery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-tools/dist/implementsAbstractType.js' {
  declare module.exports: $Exports<'graphql-tools/dist/implementsAbstractType'>;
}
declare module 'graphql-tools/dist/index.js' {
  declare module.exports: $Exports<'graphql-tools/dist/index'>;
}
declare module 'graphql-tools/dist/Interfaces.js' {
  declare module.exports: $Exports<'graphql-tools/dist/Interfaces'>;
}
declare module 'graphql-tools/dist/isEmptyObject.js' {
  declare module.exports: $Exports<'graphql-tools/dist/isEmptyObject'>;
}
declare module 'graphql-tools/dist/isSpecifiedScalarType.js' {
  declare module.exports: $Exports<'graphql-tools/dist/isSpecifiedScalarType'>;
}
declare module 'graphql-tools/dist/Logger.js' {
  declare module.exports: $Exports<'graphql-tools/dist/Logger'>;
}
declare module 'graphql-tools/dist/mergeDeep.js' {
  declare module.exports: $Exports<'graphql-tools/dist/mergeDeep'>;
}
declare module 'graphql-tools/dist/mock.js' {
  declare module.exports: $Exports<'graphql-tools/dist/mock'>;
}
declare module 'graphql-tools/dist/schemaGenerator.js' {
  declare module.exports: $Exports<'graphql-tools/dist/schemaGenerator'>;
}
declare module 'graphql-tools/dist/schemaVisitor.js' {
  declare module.exports: $Exports<'graphql-tools/dist/schemaVisitor'>;
}
declare module 'graphql-tools/dist/stitching/defaultMergedResolver.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/defaultMergedResolver'>;
}
declare module 'graphql-tools/dist/stitching/delegateToSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/delegateToSchema'>;
}
declare module 'graphql-tools/dist/stitching/errors.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/errors'>;
}
declare module 'graphql-tools/dist/stitching/index.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/index'>;
}
declare module 'graphql-tools/dist/stitching/introspectSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/introspectSchema'>;
}
declare module 'graphql-tools/dist/stitching/linkToFetcher.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/linkToFetcher'>;
}
declare module 'graphql-tools/dist/stitching/makeRemoteExecutableSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/makeRemoteExecutableSchema'>;
}
declare module 'graphql-tools/dist/stitching/mergeSchemas.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/mergeSchemas'>;
}
declare module 'graphql-tools/dist/stitching/observableToAsyncIterable.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/observableToAsyncIterable'>;
}
declare module 'graphql-tools/dist/stitching/resolveFromParentTypename.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/resolveFromParentTypename'>;
}
declare module 'graphql-tools/dist/stitching/resolvers.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/resolvers'>;
}
declare module 'graphql-tools/dist/stitching/schemaRecreation.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/schemaRecreation'>;
}
declare module 'graphql-tools/dist/stitching/typeFromAST.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/typeFromAST'>;
}
declare module 'graphql-tools/dist/transforms/AddArgumentsAsVariables.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/AddArgumentsAsVariables'>;
}
declare module 'graphql-tools/dist/transforms/AddTypenameToAbstract.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/AddTypenameToAbstract'>;
}
declare module 'graphql-tools/dist/transforms/CheckResultAndHandleErrors.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/CheckResultAndHandleErrors'>;
}
declare module 'graphql-tools/dist/transforms/ExpandAbstractTypes.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/ExpandAbstractTypes'>;
}
declare module 'graphql-tools/dist/transforms/ExtractField.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/ExtractField'>;
}
declare module 'graphql-tools/dist/transforms/FilterRootFields.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/FilterRootFields'>;
}
declare module 'graphql-tools/dist/transforms/FilterToSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/FilterToSchema'>;
}
declare module 'graphql-tools/dist/transforms/FilterTypes.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/FilterTypes'>;
}
declare module 'graphql-tools/dist/transforms/index.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/index'>;
}
declare module 'graphql-tools/dist/transforms/RenameRootFields.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/RenameRootFields'>;
}
declare module 'graphql-tools/dist/transforms/RenameTypes.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/RenameTypes'>;
}
declare module 'graphql-tools/dist/transforms/ReplaceFieldWithFragment.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/ReplaceFieldWithFragment'>;
}
declare module 'graphql-tools/dist/transforms/TransformRootFields.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/TransformRootFields'>;
}
declare module 'graphql-tools/dist/transforms/transforms.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/transforms'>;
}
declare module 'graphql-tools/dist/transforms/transformSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/transformSchema'>;
}
declare module 'graphql-tools/dist/transforms/visitSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/visitSchema'>;
}
declare module 'graphql-tools/dist/transforms/WrapQuery.js' {
  declare module.exports: $Exports<'graphql-tools/dist/transforms/WrapQuery'>;
}
