// flow-typed signature: 803f1660d6fc73427f1381ed7236bc22
// flow-typed version: <<STUB>>/graphql-input-string_v0.0.16/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-input-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-input-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-input-string/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-input-string/lib/index.js' {
  declare module.exports: $Exports<'graphql-input-string/lib/index'>;
}
