// flow-typed signature: 679264f13ffd438a21f0637c649ac3d1
// flow-typed version: <<STUB>>/graphql-errors_v2.1.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-errors/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-errors/scripts/mocha_runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-errors/dist/index.js' {
  declare module.exports: $Exports<'graphql-errors/dist/index'>;
}
declare module 'graphql-errors/index' {
  declare module.exports: $Exports<'graphql-errors'>;
}
declare module 'graphql-errors/index.js' {
  declare module.exports: $Exports<'graphql-errors'>;
}
declare module 'graphql-errors/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'graphql-errors/scripts/mocha_runner'>;
}
