// flow-typed signature: 44f2c6df50d26b4d16bd31566391396c
// flow-typed version: <<STUB>>/graphql-input-number_v0.0.10/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-input-number'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-input-number' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-input-number/lib/float' {
  declare module.exports: any;
}

declare module 'graphql-input-number/lib/index' {
  declare module.exports: any;
}

declare module 'graphql-input-number/lib/int' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-input-number/lib/float.js' {
  declare module.exports: $Exports<'graphql-input-number/lib/float'>;
}
declare module 'graphql-input-number/lib/index.js' {
  declare module.exports: $Exports<'graphql-input-number/lib/index'>;
}
declare module 'graphql-input-number/lib/int.js' {
  declare module.exports: $Exports<'graphql-input-number/lib/int'>;
}
