// flow-typed signature: 3f632ee4df8f11c4f9a5dfe96881efeb
// flow-typed version: <<STUB>>/graphql-custom-types_v1.4.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-custom-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-custom-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-custom-types/lib/factory' {
  declare module.exports: any;
}

declare module 'graphql-custom-types/lib/index' {
  declare module.exports: any;
}

declare module 'graphql-custom-types/lib/scalars' {
  declare module.exports: any;
}

declare module 'graphql-custom-types/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-custom-types/lib/factory.js' {
  declare module.exports: $Exports<'graphql-custom-types/lib/factory'>;
}
declare module 'graphql-custom-types/lib/index.js' {
  declare module.exports: $Exports<'graphql-custom-types/lib/index'>;
}
declare module 'graphql-custom-types/lib/scalars.js' {
  declare module.exports: $Exports<'graphql-custom-types/lib/scalars'>;
}
declare module 'graphql-custom-types/lib/types.js' {
  declare module.exports: $Exports<'graphql-custom-types/lib/types'>;
}
