// flow-typed signature: de66307aee10778f406c80943a6e55d0
// flow-typed version: <<STUB>>/html-loader-jest_v0.2.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-loader-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-loader-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-loader-jest/index' {
  declare module.exports: $Exports<'html-loader-jest'>;
}
declare module 'html-loader-jest/index.js' {
  declare module.exports: $Exports<'html-loader-jest'>;
}
