// flow-typed signature: aac27f140d99af565a436ff29112a3a3
// flow-typed version: <<STUB>>/maildev_v1.0.0-rc3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'maildev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'maildev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'maildev/app/components/angular-cookies/angular-cookies' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular-cookies/angular-cookies.min' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular-resource/angular-resource' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular-resource/angular-resource.min' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular-route/angular-route' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular-route/angular-route.min' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular-sanitize/angular-sanitize' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular-sanitize/angular-sanitize.min' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular/angular' {
  declare module.exports: any;
}

declare module 'maildev/app/components/angular/angular.min' {
  declare module.exports: any;
}

declare module 'maildev/app/scripts/app' {
  declare module.exports: any;
}

declare module 'maildev/app/scripts/controllers/item' {
  declare module.exports: any;
}

declare module 'maildev/app/scripts/controllers/main' {
  declare module.exports: any;
}

declare module 'maildev/app/scripts/services' {
  declare module.exports: any;
}

declare module 'maildev/lib/auth' {
  declare module.exports: any;
}

declare module 'maildev/lib/helpers/smtp' {
  declare module.exports: any;
}

declare module 'maildev/lib/logger' {
  declare module.exports: any;
}

declare module 'maildev/lib/mailserver' {
  declare module.exports: any;
}

declare module 'maildev/lib/outgoing' {
  declare module.exports: any;
}

declare module 'maildev/lib/routes' {
  declare module.exports: any;
}

declare module 'maildev/lib/utils' {
  declare module.exports: any;
}

declare module 'maildev/lib/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'maildev/app/components/angular-cookies/angular-cookies.js' {
  declare module.exports: $Exports<'maildev/app/components/angular-cookies/angular-cookies'>;
}
declare module 'maildev/app/components/angular-cookies/angular-cookies.min.js' {
  declare module.exports: $Exports<'maildev/app/components/angular-cookies/angular-cookies.min'>;
}
declare module 'maildev/app/components/angular-resource/angular-resource.js' {
  declare module.exports: $Exports<'maildev/app/components/angular-resource/angular-resource'>;
}
declare module 'maildev/app/components/angular-resource/angular-resource.min.js' {
  declare module.exports: $Exports<'maildev/app/components/angular-resource/angular-resource.min'>;
}
declare module 'maildev/app/components/angular-route/angular-route.js' {
  declare module.exports: $Exports<'maildev/app/components/angular-route/angular-route'>;
}
declare module 'maildev/app/components/angular-route/angular-route.min.js' {
  declare module.exports: $Exports<'maildev/app/components/angular-route/angular-route.min'>;
}
declare module 'maildev/app/components/angular-sanitize/angular-sanitize.js' {
  declare module.exports: $Exports<'maildev/app/components/angular-sanitize/angular-sanitize'>;
}
declare module 'maildev/app/components/angular-sanitize/angular-sanitize.min.js' {
  declare module.exports: $Exports<'maildev/app/components/angular-sanitize/angular-sanitize.min'>;
}
declare module 'maildev/app/components/angular/angular.js' {
  declare module.exports: $Exports<'maildev/app/components/angular/angular'>;
}
declare module 'maildev/app/components/angular/angular.min.js' {
  declare module.exports: $Exports<'maildev/app/components/angular/angular.min'>;
}
declare module 'maildev/app/scripts/app.js' {
  declare module.exports: $Exports<'maildev/app/scripts/app'>;
}
declare module 'maildev/app/scripts/controllers/item.js' {
  declare module.exports: $Exports<'maildev/app/scripts/controllers/item'>;
}
declare module 'maildev/app/scripts/controllers/main.js' {
  declare module.exports: $Exports<'maildev/app/scripts/controllers/main'>;
}
declare module 'maildev/app/scripts/services.js' {
  declare module.exports: $Exports<'maildev/app/scripts/services'>;
}
declare module 'maildev/index' {
  declare module.exports: $Exports<'maildev'>;
}
declare module 'maildev/index.js' {
  declare module.exports: $Exports<'maildev'>;
}
declare module 'maildev/lib/auth.js' {
  declare module.exports: $Exports<'maildev/lib/auth'>;
}
declare module 'maildev/lib/helpers/smtp.js' {
  declare module.exports: $Exports<'maildev/lib/helpers/smtp'>;
}
declare module 'maildev/lib/logger.js' {
  declare module.exports: $Exports<'maildev/lib/logger'>;
}
declare module 'maildev/lib/mailserver.js' {
  declare module.exports: $Exports<'maildev/lib/mailserver'>;
}
declare module 'maildev/lib/outgoing.js' {
  declare module.exports: $Exports<'maildev/lib/outgoing'>;
}
declare module 'maildev/lib/routes.js' {
  declare module.exports: $Exports<'maildev/lib/routes'>;
}
declare module 'maildev/lib/utils.js' {
  declare module.exports: $Exports<'maildev/lib/utils'>;
}
declare module 'maildev/lib/web.js' {
  declare module.exports: $Exports<'maildev/lib/web'>;
}
