// flow-typed signature: cd11d32400baedfeb503883bd6279d81
// flow-typed version: <<STUB>>/merge-graphql-schemas_v1.5.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'merge-graphql-schemas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'merge-graphql-schemas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'merge-graphql-schemas/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'merge-graphql-schemas/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'merge-graphql-schemas/dist/index.cjs.js' {
  declare module.exports: $Exports<'merge-graphql-schemas/dist/index.cjs'>;
}
declare module 'merge-graphql-schemas/dist/index.esm.js' {
  declare module.exports: $Exports<'merge-graphql-schemas/dist/index.esm'>;
}
