// flow-typed signature: b799f003381de825b4bc0e4ffcd5e3cf
// flow-typed version: <<STUB>>/p-each-series_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-each-series'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-each-series' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-each-series/index' {
  declare module.exports: $Exports<'p-each-series'>;
}
declare module 'p-each-series/index.js' {
  declare module.exports: $Exports<'p-each-series'>;
}
