// flow-typed signature: 1127ea896bd27ead88615ac57ac3a40f
// flow-typed version: <<STUB>>/p-reflect_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-reflect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-reflect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-reflect/index' {
  declare module.exports: $Exports<'p-reflect'>;
}
declare module 'p-reflect/index.js' {
  declare module.exports: $Exports<'p-reflect'>;
}
