// flow-typed signature: f83df22ddb7593ac523f1b55b5db94c9
// flow-typed version: <<STUB>>/proxy-validator_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proxy-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'proxy-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proxy-validator/commitlint.config' {
  declare module.exports: any;
}

declare module 'proxy-validator/lib/index' {
  declare module.exports: any;
}

declare module 'proxy-validator/rollup.config' {
  declare module.exports: any;
}

declare module 'proxy-validator/src/error' {
  declare module.exports: any;
}

declare module 'proxy-validator/src/index' {
  declare module.exports: any;
}

declare module 'proxy-validator/src/proxy' {
  declare module.exports: any;
}

declare module 'proxy-validator/src/types' {
  declare module.exports: any;
}

declare module 'proxy-validator/src/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proxy-validator/commitlint.config.js' {
  declare module.exports: $Exports<'proxy-validator/commitlint.config'>;
}
declare module 'proxy-validator/lib/index.js' {
  declare module.exports: $Exports<'proxy-validator/lib/index'>;
}
declare module 'proxy-validator/rollup.config.js' {
  declare module.exports: $Exports<'proxy-validator/rollup.config'>;
}
declare module 'proxy-validator/src/error.js' {
  declare module.exports: $Exports<'proxy-validator/src/error'>;
}
declare module 'proxy-validator/src/index.js' {
  declare module.exports: $Exports<'proxy-validator/src/index'>;
}
declare module 'proxy-validator/src/proxy.js' {
  declare module.exports: $Exports<'proxy-validator/src/proxy'>;
}
declare module 'proxy-validator/src/types.js' {
  declare module.exports: $Exports<'proxy-validator/src/types'>;
}
declare module 'proxy-validator/src/validation.js' {
  declare module.exports: $Exports<'proxy-validator/src/validation'>;
}
