// flow-typed signature: f9c931f4730846a6233a8baff15d37a3
// flow-typed version: <<STUB>>/react-confirm-alert_v^2.0.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-confirm-alert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-confirm-alert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-confirm-alert/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-confirm-alert/lib/index.js' {
  declare module.exports: $Exports<'react-confirm-alert/lib/index'>;
}
