// flow-typed signature: 143e215c255765ab3ff0a57f73af0cbc
// flow-typed version: <<STUB>>/react-google-maps_v9.4.5/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-maps/lib/components/addons/InfoBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/addons/MarkerClusterer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/addons/MarkerWithLabel' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/BicyclingLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Circle' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/DirectionsRenderer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/drawing/DrawingManager' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/FusionTablesLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/GoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/GroundOverlay' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/InfoWindow' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/KmlLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Marker' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/OverlayView' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/places/SearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/places/StandaloneSearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Polygon' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Polyline' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Rectangle' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/StreetViewPanorama' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/TrafficLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/visualization/HeatmapLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/constants' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/index' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/MapChildHelper' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/OverlayViewHelper' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/withGoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/withScriptjs' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/addons/__tests__/InfoBox.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/addons/__tests__/MarkerClusterer.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/addons/InfoBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/addons/MarkerClusterer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/addons/MarkerWithLabel' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/BicyclingLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/Circle' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/DirectionsRenderer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/drawing/__tests__/DrawingManager.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/drawing/DrawingManager' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/FusionTablesLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/GoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/GroundOverlay' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/InfoWindow' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/KmlLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/Marker' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/OverlayView' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/places/__tests__/SearchBox.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/places/SearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/places/StandaloneSearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/Polygon' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/Polyline' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/Rectangle' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/StreetViewPanorama' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/TrafficLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/visualization/__tests__/HeatmapLayer.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/components/visualization/HeatmapLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/constants' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/index' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/addons/MarkerWithLabel' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/BicyclingLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/Circle' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/DirectionsRenderer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/drawing/DrawingManager' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/FusionTablesLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/GoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/GroundOverlay' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/InfoWindow' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/KmlLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/Marker' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/OverlayView' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/places/SearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/places/StandaloneSearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/Polygon' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/Polyline' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/Rectangle' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/StreetViewPanorama' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/TrafficLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/macros/visualization/HeatmapLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/tx/ClassDefinition' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/tx/jscodeshift' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/tx/MapChild' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/MapChildHelper' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/OverlayViewHelper' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/withGoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/withScriptjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-maps/lib/components/addons/InfoBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/addons/InfoBox'>;
}
declare module 'react-google-maps/lib/components/addons/MarkerClusterer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/addons/MarkerClusterer'>;
}
declare module 'react-google-maps/lib/components/addons/MarkerWithLabel.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/addons/MarkerWithLabel'>;
}
declare module 'react-google-maps/lib/components/BicyclingLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/BicyclingLayer'>;
}
declare module 'react-google-maps/lib/components/Circle.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Circle'>;
}
declare module 'react-google-maps/lib/components/DirectionsRenderer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/DirectionsRenderer'>;
}
declare module 'react-google-maps/lib/components/drawing/DrawingManager.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/drawing/DrawingManager'>;
}
declare module 'react-google-maps/lib/components/FusionTablesLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/FusionTablesLayer'>;
}
declare module 'react-google-maps/lib/components/GoogleMap.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/GoogleMap'>;
}
declare module 'react-google-maps/lib/components/GroundOverlay.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/GroundOverlay'>;
}
declare module 'react-google-maps/lib/components/InfoWindow.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/InfoWindow'>;
}
declare module 'react-google-maps/lib/components/KmlLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/KmlLayer'>;
}
declare module 'react-google-maps/lib/components/Marker.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Marker'>;
}
declare module 'react-google-maps/lib/components/OverlayView.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/OverlayView'>;
}
declare module 'react-google-maps/lib/components/places/SearchBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/places/SearchBox'>;
}
declare module 'react-google-maps/lib/components/places/StandaloneSearchBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/places/StandaloneSearchBox'>;
}
declare module 'react-google-maps/lib/components/Polygon.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Polygon'>;
}
declare module 'react-google-maps/lib/components/Polyline.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Polyline'>;
}
declare module 'react-google-maps/lib/components/Rectangle.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Rectangle'>;
}
declare module 'react-google-maps/lib/components/StreetViewPanorama.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/StreetViewPanorama'>;
}
declare module 'react-google-maps/lib/components/TrafficLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/TrafficLayer'>;
}
declare module 'react-google-maps/lib/components/visualization/HeatmapLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/visualization/HeatmapLayer'>;
}
declare module 'react-google-maps/lib/constants.js' {
  declare module.exports: $Exports<'react-google-maps/lib/constants'>;
}
declare module 'react-google-maps/lib/index.js' {
  declare module.exports: $Exports<'react-google-maps/lib/index'>;
}
declare module 'react-google-maps/lib/utils/MapChildHelper.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/MapChildHelper'>;
}
declare module 'react-google-maps/lib/utils/OverlayViewHelper.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/OverlayViewHelper'>;
}
declare module 'react-google-maps/lib/withGoogleMap.js' {
  declare module.exports: $Exports<'react-google-maps/lib/withGoogleMap'>;
}
declare module 'react-google-maps/lib/withScriptjs.js' {
  declare module.exports: $Exports<'react-google-maps/lib/withScriptjs'>;
}
declare module 'react-google-maps/src/__tests__/index.spec.js' {
  declare module.exports: $Exports<'react-google-maps/src/__tests__/index.spec'>;
}
declare module 'react-google-maps/src/components/addons/__tests__/InfoBox.spec.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/addons/__tests__/InfoBox.spec'>;
}
declare module 'react-google-maps/src/components/addons/__tests__/MarkerClusterer.spec.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/addons/__tests__/MarkerClusterer.spec'>;
}
declare module 'react-google-maps/src/components/addons/InfoBox.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/addons/InfoBox'>;
}
declare module 'react-google-maps/src/components/addons/MarkerClusterer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/addons/MarkerClusterer'>;
}
declare module 'react-google-maps/src/components/addons/MarkerWithLabel.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/addons/MarkerWithLabel'>;
}
declare module 'react-google-maps/src/components/BicyclingLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/BicyclingLayer'>;
}
declare module 'react-google-maps/src/components/Circle.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/Circle'>;
}
declare module 'react-google-maps/src/components/DirectionsRenderer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/DirectionsRenderer'>;
}
declare module 'react-google-maps/src/components/drawing/__tests__/DrawingManager.spec.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/drawing/__tests__/DrawingManager.spec'>;
}
declare module 'react-google-maps/src/components/drawing/DrawingManager.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/drawing/DrawingManager'>;
}
declare module 'react-google-maps/src/components/FusionTablesLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/FusionTablesLayer'>;
}
declare module 'react-google-maps/src/components/GoogleMap.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/GoogleMap'>;
}
declare module 'react-google-maps/src/components/GroundOverlay.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/GroundOverlay'>;
}
declare module 'react-google-maps/src/components/InfoWindow.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/InfoWindow'>;
}
declare module 'react-google-maps/src/components/KmlLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/KmlLayer'>;
}
declare module 'react-google-maps/src/components/Marker.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/Marker'>;
}
declare module 'react-google-maps/src/components/OverlayView.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/OverlayView'>;
}
declare module 'react-google-maps/src/components/places/__tests__/SearchBox.spec.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/places/__tests__/SearchBox.spec'>;
}
declare module 'react-google-maps/src/components/places/SearchBox.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/places/SearchBox'>;
}
declare module 'react-google-maps/src/components/places/StandaloneSearchBox.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/places/StandaloneSearchBox'>;
}
declare module 'react-google-maps/src/components/Polygon.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/Polygon'>;
}
declare module 'react-google-maps/src/components/Polyline.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/Polyline'>;
}
declare module 'react-google-maps/src/components/Rectangle.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/Rectangle'>;
}
declare module 'react-google-maps/src/components/StreetViewPanorama.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/StreetViewPanorama'>;
}
declare module 'react-google-maps/src/components/TrafficLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/TrafficLayer'>;
}
declare module 'react-google-maps/src/components/visualization/__tests__/HeatmapLayer.spec.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/visualization/__tests__/HeatmapLayer.spec'>;
}
declare module 'react-google-maps/src/components/visualization/HeatmapLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/components/visualization/HeatmapLayer'>;
}
declare module 'react-google-maps/src/constants.js' {
  declare module.exports: $Exports<'react-google-maps/src/constants'>;
}
declare module 'react-google-maps/src/index.js' {
  declare module.exports: $Exports<'react-google-maps/src/index'>;
}
declare module 'react-google-maps/src/macros/addons/MarkerWithLabel.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/addons/MarkerWithLabel'>;
}
declare module 'react-google-maps/src/macros/BicyclingLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/BicyclingLayer'>;
}
declare module 'react-google-maps/src/macros/Circle.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/Circle'>;
}
declare module 'react-google-maps/src/macros/DirectionsRenderer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/DirectionsRenderer'>;
}
declare module 'react-google-maps/src/macros/drawing/DrawingManager.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/drawing/DrawingManager'>;
}
declare module 'react-google-maps/src/macros/FusionTablesLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/FusionTablesLayer'>;
}
declare module 'react-google-maps/src/macros/GoogleMap.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/GoogleMap'>;
}
declare module 'react-google-maps/src/macros/GroundOverlay.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/GroundOverlay'>;
}
declare module 'react-google-maps/src/macros/InfoWindow.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/InfoWindow'>;
}
declare module 'react-google-maps/src/macros/KmlLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/KmlLayer'>;
}
declare module 'react-google-maps/src/macros/Marker.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/Marker'>;
}
declare module 'react-google-maps/src/macros/OverlayView.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/OverlayView'>;
}
declare module 'react-google-maps/src/macros/places/SearchBox.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/places/SearchBox'>;
}
declare module 'react-google-maps/src/macros/places/StandaloneSearchBox.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/places/StandaloneSearchBox'>;
}
declare module 'react-google-maps/src/macros/Polygon.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/Polygon'>;
}
declare module 'react-google-maps/src/macros/Polyline.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/Polyline'>;
}
declare module 'react-google-maps/src/macros/Rectangle.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/Rectangle'>;
}
declare module 'react-google-maps/src/macros/StreetViewPanorama.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/StreetViewPanorama'>;
}
declare module 'react-google-maps/src/macros/TrafficLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/TrafficLayer'>;
}
declare module 'react-google-maps/src/macros/visualization/HeatmapLayer.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/macros/visualization/HeatmapLayer'>;
}
declare module 'react-google-maps/src/tx/ClassDefinition.js' {
  declare module.exports: $Exports<'react-google-maps/src/tx/ClassDefinition'>;
}
declare module 'react-google-maps/src/tx/jscodeshift.js' {
  declare module.exports: $Exports<'react-google-maps/src/tx/jscodeshift'>;
}
declare module 'react-google-maps/src/tx/MapChild.js' {
  declare module.exports: $Exports<'react-google-maps/src/tx/MapChild'>;
}
declare module 'react-google-maps/src/utils/MapChildHelper.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/MapChildHelper'>;
}
declare module 'react-google-maps/src/utils/OverlayViewHelper.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/OverlayViewHelper'>;
}
declare module 'react-google-maps/src/withGoogleMap.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/withGoogleMap'>;
}
declare module 'react-google-maps/src/withScriptjs.jsx' {
  declare module.exports: $Exports<'react-google-maps/src/withScriptjs'>;
}
