// flow-typed signature: e9da99d71204a6ad4750198ba4796f12
// flow-typed version: <<STUB>>/react-confirm-alert_v2.0.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-confirm-alert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-confirm-alert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-confirm-alert/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-confirm-alert/lib/index.js' {
  declare module.exports: $Exports<'react-confirm-alert/lib/index'>;
}
