// flow-typed signature: 606e7c1703eb03349b7b186445565429
// flow-typed version: <<STUB>>/react-progressive-bg-image_v3.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-progressive-bg-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-progressive-bg-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-progressive-bg-image/lib/Img' {
  declare module.exports: any;
}

declare module 'react-progressive-bg-image/lib/index' {
  declare module.exports: any;
}

declare module 'react-progressive-bg-image/lib/loadImage' {
  declare module.exports: any;
}

declare module 'react-progressive-bg-image/lib/ProgressiveImage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-progressive-bg-image/lib/Img.js' {
  declare module.exports: $Exports<'react-progressive-bg-image/lib/Img'>;
}
declare module 'react-progressive-bg-image/lib/index.js' {
  declare module.exports: $Exports<'react-progressive-bg-image/lib/index'>;
}
declare module 'react-progressive-bg-image/lib/loadImage.js' {
  declare module.exports: $Exports<'react-progressive-bg-image/lib/loadImage'>;
}
declare module 'react-progressive-bg-image/lib/ProgressiveImage.js' {
  declare module.exports: $Exports<'react-progressive-bg-image/lib/ProgressiveImage'>;
}
