// flow-typed signature: 95879544e688f51834d81cb7f6cf5b89
// flow-typed version: <<STUB>>/reset-css_v3.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reset-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reset-css' {
  declare module.exports: any;
}
