// flow-typed signature: c0c13b6a034e7cdf2c923312249b2be8
// flow-typed version: <<STUB>>/serverless-offline_v3.25.5/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-offline/manual_test/handler' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/authCanExecuteResource' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/authMatchPolicyResource' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/createAuthScheme' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/createLambdaContext' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/createLambdaProxyContext' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/createVelocityContext' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/debugLog' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/Endpoint' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/functionHelper' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/index' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/javaHelper' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/jsonPath' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/parseResources' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/renderVelocityTemplateObject' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/utils' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/integration/offline' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/support/OffLineBuilder' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/support/RequestBuilder' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/support/ServerlessBuilder' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/unit/authCanExecuteResourceTest' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/unit/authMatchPolicyResourceTest' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/unit/createLambdaProxyContextTest' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/unit/functionHelperTest' {
  declare module.exports: any;
}

declare module 'serverless-offline/test/unit/utilsTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-offline/manual_test/handler.js' {
  declare module.exports: $Exports<'serverless-offline/manual_test/handler'>;
}
declare module 'serverless-offline/src/authCanExecuteResource.js' {
  declare module.exports: $Exports<'serverless-offline/src/authCanExecuteResource'>;
}
declare module 'serverless-offline/src/authMatchPolicyResource.js' {
  declare module.exports: $Exports<'serverless-offline/src/authMatchPolicyResource'>;
}
declare module 'serverless-offline/src/createAuthScheme.js' {
  declare module.exports: $Exports<'serverless-offline/src/createAuthScheme'>;
}
declare module 'serverless-offline/src/createLambdaContext.js' {
  declare module.exports: $Exports<'serverless-offline/src/createLambdaContext'>;
}
declare module 'serverless-offline/src/createLambdaProxyContext.js' {
  declare module.exports: $Exports<'serverless-offline/src/createLambdaProxyContext'>;
}
declare module 'serverless-offline/src/createVelocityContext.js' {
  declare module.exports: $Exports<'serverless-offline/src/createVelocityContext'>;
}
declare module 'serverless-offline/src/debugLog.js' {
  declare module.exports: $Exports<'serverless-offline/src/debugLog'>;
}
declare module 'serverless-offline/src/Endpoint.js' {
  declare module.exports: $Exports<'serverless-offline/src/Endpoint'>;
}
declare module 'serverless-offline/src/functionHelper.js' {
  declare module.exports: $Exports<'serverless-offline/src/functionHelper'>;
}
declare module 'serverless-offline/src/index.js' {
  declare module.exports: $Exports<'serverless-offline/src/index'>;
}
declare module 'serverless-offline/src/javaHelper.js' {
  declare module.exports: $Exports<'serverless-offline/src/javaHelper'>;
}
declare module 'serverless-offline/src/jsonPath.js' {
  declare module.exports: $Exports<'serverless-offline/src/jsonPath'>;
}
declare module 'serverless-offline/src/parseResources.js' {
  declare module.exports: $Exports<'serverless-offline/src/parseResources'>;
}
declare module 'serverless-offline/src/renderVelocityTemplateObject.js' {
  declare module.exports: $Exports<'serverless-offline/src/renderVelocityTemplateObject'>;
}
declare module 'serverless-offline/src/utils.js' {
  declare module.exports: $Exports<'serverless-offline/src/utils'>;
}
declare module 'serverless-offline/test/integration/offline.js' {
  declare module.exports: $Exports<'serverless-offline/test/integration/offline'>;
}
declare module 'serverless-offline/test/support/OffLineBuilder.js' {
  declare module.exports: $Exports<'serverless-offline/test/support/OffLineBuilder'>;
}
declare module 'serverless-offline/test/support/RequestBuilder.js' {
  declare module.exports: $Exports<'serverless-offline/test/support/RequestBuilder'>;
}
declare module 'serverless-offline/test/support/ServerlessBuilder.js' {
  declare module.exports: $Exports<'serverless-offline/test/support/ServerlessBuilder'>;
}
declare module 'serverless-offline/test/unit/authCanExecuteResourceTest.js' {
  declare module.exports: $Exports<'serverless-offline/test/unit/authCanExecuteResourceTest'>;
}
declare module 'serverless-offline/test/unit/authMatchPolicyResourceTest.js' {
  declare module.exports: $Exports<'serverless-offline/test/unit/authMatchPolicyResourceTest'>;
}
declare module 'serverless-offline/test/unit/createLambdaProxyContextTest.js' {
  declare module.exports: $Exports<'serverless-offline/test/unit/createLambdaProxyContextTest'>;
}
declare module 'serverless-offline/test/unit/functionHelperTest.js' {
  declare module.exports: $Exports<'serverless-offline/test/unit/functionHelperTest'>;
}
declare module 'serverless-offline/test/unit/utilsTest.js' {
  declare module.exports: $Exports<'serverless-offline/test/unit/utilsTest'>;
}
