// flow-typed signature: c0316690e596f84d0deeb5e28ef2d179
// flow-typed version: <<STUB>>/serverless-plugin-warmup_v3.6.1-rc.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-plugin-warmup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-plugin-warmup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-plugin-warmup/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-plugin-warmup/src/index.js' {
  declare module.exports: $Exports<'serverless-plugin-warmup/src/index'>;
}
