// flow-typed signature: a19e0fe00d0adc550abdf8faf7dc7888
// flow-typed version: <<STUB>>/serverless-content-encoding_v1.1.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-content-encoding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-content-encoding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-content-encoding/src/index' {
  declare module.exports: any;
}

declare module 'serverless-content-encoding/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-content-encoding/src/index.js' {
  declare module.exports: $Exports<'serverless-content-encoding/src/index'>;
}
declare module 'serverless-content-encoding/tests/index.test.js' {
  declare module.exports: $Exports<'serverless-content-encoding/tests/index.test'>;
}
