// flow-typed signature: 3616dd51d80acb6f6b083a1f4a72bf08
// flow-typed version: <<STUB>>/serverless-content-encoding_v1.0.22/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-content-encoding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-content-encoding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-content-encoding/src/index' {
  declare module.exports: any;
}

declare module 'serverless-content-encoding/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-content-encoding/src/index.js' {
  declare module.exports: $Exports<'serverless-content-encoding/src/index'>;
}
declare module 'serverless-content-encoding/tests/index.test.js' {
  declare module.exports: $Exports<'serverless-content-encoding/tests/index.test'>;
}
