// flow-typed signature: b024181277c7a10c1cb1695b2a68290b
// flow-typed version: <<STUB>>/serverless-s3-deploy_v0.7.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-s3-deploy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-s3-deploy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'serverless-s3-deploy/index' {
  declare module.exports: $Exports<'serverless-s3-deploy'>;
}
declare module 'serverless-s3-deploy/index.js' {
  declare module.exports: $Exports<'serverless-s3-deploy'>;
}
