// flow-typed signature: 0850f3f0966523a4336eb1e7750f6a21
// flow-typed version: <<STUB>>/serverless-domain-manager_v2.4.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-domain-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-domain-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-domain-manager/DomainResponse' {
  declare module.exports: any;
}

declare module 'serverless-domain-manager/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-domain-manager/DomainResponse.js' {
  declare module.exports: $Exports<'serverless-domain-manager/DomainResponse'>;
}
declare module 'serverless-domain-manager/index' {
  declare module.exports: $Exports<'serverless-domain-manager'>;
}
declare module 'serverless-domain-manager/index.js' {
  declare module.exports: $Exports<'serverless-domain-manager'>;
}
declare module 'serverless-domain-manager/test/index.test.js' {
  declare module.exports: $Exports<'serverless-domain-manager/test/index.test'>;
}
