// flow-typed signature: c5882bb30ce2013ffd38136660edb8c7
// flow-typed version: <<STUB>>/stickybits_v3.3.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stickybits'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stickybits' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stickybits/dist/jquery.stickybits' {
  declare module.exports: any;
}

declare module 'stickybits/dist/jquery.stickybits.min' {
  declare module.exports: any;
}

declare module 'stickybits/dist/stickybits.es' {
  declare module.exports: any;
}

declare module 'stickybits/dist/stickybits' {
  declare module.exports: any;
}

declare module 'stickybits/dist/stickybits.min' {
  declare module.exports: any;
}

declare module 'stickybits/dist/umbrella.stickybits' {
  declare module.exports: any;
}

declare module 'stickybits/src/jquery.stickybits' {
  declare module.exports: any;
}

declare module 'stickybits/src/stickybits' {
  declare module.exports: any;
}

declare module 'stickybits/src/umbrella.stickybits' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stickybits/dist/jquery.stickybits.js' {
  declare module.exports: $Exports<'stickybits/dist/jquery.stickybits'>;
}
declare module 'stickybits/dist/jquery.stickybits.min.js' {
  declare module.exports: $Exports<'stickybits/dist/jquery.stickybits.min'>;
}
declare module 'stickybits/dist/stickybits.es.js' {
  declare module.exports: $Exports<'stickybits/dist/stickybits.es'>;
}
declare module 'stickybits/dist/stickybits.js' {
  declare module.exports: $Exports<'stickybits/dist/stickybits'>;
}
declare module 'stickybits/dist/stickybits.min.js' {
  declare module.exports: $Exports<'stickybits/dist/stickybits.min'>;
}
declare module 'stickybits/dist/umbrella.stickybits.js' {
  declare module.exports: $Exports<'stickybits/dist/umbrella.stickybits'>;
}
declare module 'stickybits/src/jquery.stickybits.js' {
  declare module.exports: $Exports<'stickybits/src/jquery.stickybits'>;
}
declare module 'stickybits/src/stickybits.js' {
  declare module.exports: $Exports<'stickybits/src/stickybits'>;
}
declare module 'stickybits/src/umbrella.stickybits.js' {
  declare module.exports: $Exports<'stickybits/src/umbrella.stickybits'>;
}
