// flow-typed signature: 091c55e65216cd7541a7bac4d8bd3621
// flow-typed version: <<STUB>>/webpack-permissions-plugin_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-permissions-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-permissions-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-permissions-plugin/index' {
  declare module.exports: $Exports<'webpack-permissions-plugin'>;
}
declare module 'webpack-permissions-plugin/index.js' {
  declare module.exports: $Exports<'webpack-permissions-plugin'>;
}
