// flow-typed signature: 8ea95670537791822a24a2b80093197f
// flow-typed version: <<STUB>>/webpack-plugin-copy_v1.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-plugin-copy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-plugin-copy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-plugin-copy/dist/index' {
  declare module.exports: any;
}

declare module 'webpack-plugin-copy/dist/preProcessPattern' {
  declare module.exports: any;
}

declare module 'webpack-plugin-copy/dist/processPattern' {
  declare module.exports: any;
}

declare module 'webpack-plugin-copy/dist/writeFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-plugin-copy/dist/index.js' {
  declare module.exports: $Exports<'webpack-plugin-copy/dist/index'>;
}
declare module 'webpack-plugin-copy/dist/preProcessPattern.js' {
  declare module.exports: $Exports<'webpack-plugin-copy/dist/preProcessPattern'>;
}
declare module 'webpack-plugin-copy/dist/processPattern.js' {
  declare module.exports: $Exports<'webpack-plugin-copy/dist/processPattern'>;
}
declare module 'webpack-plugin-copy/dist/writeFile.js' {
  declare module.exports: $Exports<'webpack-plugin-copy/dist/writeFile'>;
}
