// flow-typed signature: 11d9113e01516624b7a2bd81ffa60b41
// flow-typed version: <<STUB>>/xss-filters_v1.2.7/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xss-filters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xss-filters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xss-filters/dist/xss-filters.1.2.0.min' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters.1.2.1.min' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters.1.2.2.min' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters.1.2.3.min' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters.1.2.4.min' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters.1.2.6.min' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters.1.2.7.min' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters.min-browserified' {
  declare module.exports: any;
}

declare module 'xss-filters/dist/xss-filters.min' {
  declare module.exports: any;
}

declare module 'xss-filters/Gruntfile' {
  declare module.exports: any;
}

declare module 'xss-filters/karma.conf' {
  declare module.exports: any;
}

declare module 'xss-filters/src/xss-filters' {
  declare module.exports: any;
}

declare module 'xss-filters/tests/fuzz/app' {
  declare module.exports: any;
}

declare module 'xss-filters/tests/fuzz/bin/fuzzer' {
  declare module.exports: any;
}

declare module 'xss-filters/tests/node-unit-tests' {
  declare module.exports: any;
}

declare module 'xss-filters/tests/polyfills' {
  declare module.exports: any;
}

declare module 'xss-filters/tests/unit/private-xss-filters' {
  declare module.exports: any;
}

declare module 'xss-filters/tests/unit/xss-filters' {
  declare module.exports: any;
}

declare module 'xss-filters/tests/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xss-filters/dist/xss-filters.1.2.0.min.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.1.2.0.min'>;
}
declare module 'xss-filters/dist/xss-filters.1.2.1.min.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.1.2.1.min'>;
}
declare module 'xss-filters/dist/xss-filters.1.2.2.min.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.1.2.2.min'>;
}
declare module 'xss-filters/dist/xss-filters.1.2.3.min.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.1.2.3.min'>;
}
declare module 'xss-filters/dist/xss-filters.1.2.4.min.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.1.2.4.min'>;
}
declare module 'xss-filters/dist/xss-filters.1.2.6.min.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.1.2.6.min'>;
}
declare module 'xss-filters/dist/xss-filters.1.2.7.min.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.1.2.7.min'>;
}
declare module 'xss-filters/dist/xss-filters.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters'>;
}
declare module 'xss-filters/dist/xss-filters.min-browserified.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.min-browserified'>;
}
declare module 'xss-filters/dist/xss-filters.min.js' {
  declare module.exports: $Exports<'xss-filters/dist/xss-filters.min'>;
}
declare module 'xss-filters/Gruntfile.js' {
  declare module.exports: $Exports<'xss-filters/Gruntfile'>;
}
declare module 'xss-filters/karma.conf.js' {
  declare module.exports: $Exports<'xss-filters/karma.conf'>;
}
declare module 'xss-filters/src/xss-filters.js' {
  declare module.exports: $Exports<'xss-filters/src/xss-filters'>;
}
declare module 'xss-filters/tests/fuzz/app.js' {
  declare module.exports: $Exports<'xss-filters/tests/fuzz/app'>;
}
declare module 'xss-filters/tests/fuzz/bin/fuzzer.js' {
  declare module.exports: $Exports<'xss-filters/tests/fuzz/bin/fuzzer'>;
}
declare module 'xss-filters/tests/node-unit-tests.js' {
  declare module.exports: $Exports<'xss-filters/tests/node-unit-tests'>;
}
declare module 'xss-filters/tests/polyfills.js' {
  declare module.exports: $Exports<'xss-filters/tests/polyfills'>;
}
declare module 'xss-filters/tests/unit/private-xss-filters.js' {
  declare module.exports: $Exports<'xss-filters/tests/unit/private-xss-filters'>;
}
declare module 'xss-filters/tests/unit/xss-filters.js' {
  declare module.exports: $Exports<'xss-filters/tests/unit/xss-filters'>;
}
declare module 'xss-filters/tests/utils.js' {
  declare module.exports: $Exports<'xss-filters/tests/utils'>;
}
