// flow-typed signature: 4ac9dbe1a3ba2f56916614eec2672ded
// flow-typed version: <<STUB>>/@keboola/serverless-papertrail-logging_v1.1.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@keboola/serverless-papertrail-logging'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@keboola/serverless-papertrail-logging' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@keboola/serverless-papertrail-logging/src/index' {
  declare module.exports: any;
}

declare module '@keboola/serverless-papertrail-logging/src/logger.handler' {
  declare module.exports: any;
}

// Filename aliases
declare module '@keboola/serverless-papertrail-logging/src/index.js' {
  declare module.exports: $Exports<'@keboola/serverless-papertrail-logging/src/index'>;
}
declare module '@keboola/serverless-papertrail-logging/src/logger.handler.js' {
  declare module.exports: $Exports<'@keboola/serverless-papertrail-logging/src/logger.handler'>;
}
