// flow-typed signature: 7d4265d591b8b94f92001d09f2aaee36
// flow-typed version: <<STUB>>/@aoberoi/passport-slack_v1.0.5/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@aoberoi/passport-slack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@aoberoi/passport-slack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@aoberoi/passport-slack/dist/index' {
  declare module.exports: any;
}

declare module '@aoberoi/passport-slack/dist/strategy' {
  declare module.exports: any;
}

declare module '@aoberoi/passport-slack/example/server' {
  declare module.exports: any;
}

declare module '@aoberoi/passport-slack/src/index' {
  declare module.exports: any;
}

declare module '@aoberoi/passport-slack/src/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module '@aoberoi/passport-slack/dist/index.js' {
  declare module.exports: $Exports<'@aoberoi/passport-slack/dist/index'>;
}
declare module '@aoberoi/passport-slack/dist/strategy.js' {
  declare module.exports: $Exports<'@aoberoi/passport-slack/dist/strategy'>;
}
declare module '@aoberoi/passport-slack/example/server.js' {
  declare module.exports: $Exports<'@aoberoi/passport-slack/example/server'>;
}
declare module '@aoberoi/passport-slack/src/index.js' {
  declare module.exports: $Exports<'@aoberoi/passport-slack/src/index'>;
}
declare module '@aoberoi/passport-slack/src/strategy.js' {
  declare module.exports: $Exports<'@aoberoi/passport-slack/src/strategy'>;
}
